# Generated by Django 5.2.8 on 2026-01-01 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_topictag_alter_lesson_content_type_forum_topic_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=20, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='core.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Certificate of Completion', max_length=200)),
                ('description', models.TextField(default='This is to certify that the student has successfully completed the course.')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='certificates/backgrounds/')),
                ('font_size', models.IntegerField(default=14)),
                ('text_color', models.CharField(default='#000000', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_template', to='core.course')),
            ],
        ),
    ]
