# Generated by Django 5.2.8 on 2026-01-02 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_notification_notificationpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytics_type', models.CharField(choices=[('course_enrollment', 'Course Enrollment'), ('course_completion', 'Course Completion'), ('lesson_completion', 'Lesson Completion'), ('quiz_attempt', 'Quiz Attempt'), ('assignment_submission', 'Assignment Submission'), ('forum_activity', 'Forum Activity'), ('user_engagement', 'User Engagement')], max_length=25)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField(default=1.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('enrollment_chart', 'Enrollment Chart'), ('progress_chart', 'Progress Chart'), ('grade_distribution', 'Grade Distribution'), ('recent_activities', 'Recent Activities'), ('user_statistics', 'User Statistics'), ('course_statistics', 'Course Statistics')], max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('course_performance', 'Course Performance'), ('student_progress', 'Student Progress'), ('user_engagement', 'User Engagement'), ('system_usage', 'System Usage'), ('grade_distribution', 'Grade Distribution'), ('certificate_issuance', 'Certificate Issuance')], max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_generated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
