# Generated by Django 5.2.8 on 2026-01-02 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_analytics_dashboardwidget_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyboardShortcut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_combination', models.CharField(help_text='e.g., Ctrl+S, Alt+F, Tab', max_length=20)),
                ('action', models.CharField(choices=[('navigate_home', 'Navigate to Home'), ('open_menu', 'Open Menu'), ('search_focus', 'Focus Search'), ('skip_to_content', 'Skip to Content'), ('toggle_sidebar', 'Toggle Sidebar'), ('previous_item', 'Previous Item'), ('next_item', 'Next Item'), ('select_item', 'Select Item'), ('close_modal', 'Close Modal'), ('save_changes', 'Save Changes'), ('cancel_action', 'Cancel Action')], max_length=20)),
                ('description', models.TextField()),
                ('is_global', models.BooleanField(default=True, help_text='Available on all pages')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenReaderContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_section', models.CharField(help_text='Name of the page section', max_length=100)),
                ('content_type', models.CharField(choices=[('navigation', 'Navigation'), ('form', 'Form'), ('media', 'Media'), ('data_table', 'Data Table'), ('chart', 'Chart'), ('other', 'Other')], max_length=50)),
                ('alternative_text', models.TextField(help_text='Descriptive text for screen readers')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccessibilityAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_type', models.CharField(choices=[('automated', 'Automated Scan'), ('manual', 'Manual Review'), ('user_feedback', 'User Feedback'), ('compliance_check', 'Compliance Check')], max_length=20)),
                ('findings', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccessibilitySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_contrast_mode', models.BooleanField(default=False)),
                ('large_text_mode', models.BooleanField(default=False)),
                ('reduced_motion_mode', models.BooleanField(default=False)),
                ('screen_reader_optimized', models.BooleanField(default=True)),
                ('keyboard_navigation_enabled', models.BooleanField(default=True)),
                ('focus_indicator_enabled', models.BooleanField(default=True)),
                ('caption_preference', models.BooleanField(default=True)),
                ('audio_volume_level', models.IntegerField(default=50, help_text='Default volume level (0-100)')),
                ('preferred_font_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('x-large', 'Extra Large')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
