# Generated by Django 5.2.8 on 2026-01-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_keyboardshortcut_screenreadercontent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio for instructor profile'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(default=10, help_text='Estimated duration in minutes'),
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, help_text='URL to redirect to', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_text',
            field=models.TextField(blank=True, help_text='For links or text answers', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('course_update', 'Course Update'), ('grade_update', 'Grade Update'), ('forum_post', 'Forum Post'), ('assignment_due', 'Assignment Due'), ('certificate_earned', 'Certificate Earned'), ('enrollment', 'Enrollment'), ('general', 'General'), ('message', 'Direct Message'), ('alert', 'System Alert')], default='general', max_length=20),
        ),
    ]
