# Generated by Django 5.2.8 on 2026-01-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_customuser_address_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='full_name',
            field=models.CharField(blank=True, help_text='The name as it appears on the certificate', max_length=255),
        ),
    ]
