# Generated by Django 5.2.8 on 2026-01-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_certificate_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload the company logo', null=True, upload_to='certificates/logos/'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='signature',
            field=models.ImageField(blank=True, help_text='Upload CEO signature', null=True, upload_to='certificates/signatures/'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='title',
            field=models.CharField(default='CERTIFICATE OF COMPLETION', max_length=200),
        ),
    ]
